import type { Project, ProjectDisplay, ProjectTemplate } from '../types';

export function displayTemplate(template: ProjectTemplate): ProjectDisplay {
  return {
    id: template.id,
    kind: 'template',
    name: template.name,
    shortDescription: template.description,
    category: template.category,
    memberLimit: template.recommendedMaxMembers,
    suggestedTechnologies: template.suggestedTechnologies,
    recommendedAreas: template.relatedAreas,
    difficulty: template.difficulty,
    suggestedDuration: template.suggestedDuration,
    problem: template.problem,
    objective: template.objective,
    audience: template.audience,
    suggestedFeatures: template.suggestedFeatures,
    evolutionIdeas: template.evolutionIdeas,
    acceptanceCriteria: template.acceptanceCriteria,
    type: 'Focus Project',
    suggestedRoles: template.suggestedComposition,
    possibleStacks: template.possibleStacks,
    outcomes: template.outcomes,
    members: [],
  };
}

export function displayProject(project: Project, template?: ProjectTemplate): ProjectDisplay {
  return {
    id: project.id,
    kind: 'project',
    name: project.name,
    shortDescription: project.description,
    category: project.category,
    status: project.status,
    memberLimit: project.maxMembers,
    suggestedTechnologies: project.technologies,
    recommendedAreas: project.relatedAreas,
    difficulty: project.difficulty,
    suggestedDuration: project.duration,
    moderationStatus: project.moderationStatus,
    moderationReason: project.moderationReason,
    plannedStartDate: project.plannedStartDate,
    plannedEndDate: project.plannedEndDate,
    problem: project.problem,
    audience: template?.audience,
    suggestedFeatures: template?.suggestedFeatures,
    evolutionIdeas: template?.evolutionIdeas,
    acceptanceCriteria: template?.acceptanceCriteria,
    type: 'Community Project',
    suggestedRoles: project.suggestedComposition,
    possibleStacks: project.possibleStacks,
    outcomes: project.outcomes,
    members: project.members,
    joinRequests: project.joinRequests,
    ownerId: project.ownerId,
    ownerName: project.ownerName,
    objective: project.objective,
    startedAt: project.startedAt,
    completedAt: project.completedAt,
    cancelledAt: project.cancelledAt,
    archivedAt: project.archivedAt,
    cancellationReason: project.cancellationReason,
    repositoryUrl: project.repositoryUrl,
    demoUrl: project.demoUrl,
    completionSummary: project.completionSummary,
    createdAt: project.createdAt,
  };
}
